### PR TITLE
Fix a typo in QueueAllTest

### PR DESCRIPTION
**Pull request by szepeviktor**
Just fixing that typo.

There are a few "occured" typos.
https://github.com/search?q=repo%3Aclue%2Freactphp-mq%20occured&type=code

### CODE REVIEW

**Review by clue — COMMENTED** [review]
@szepeviktor Thank you for spotting and filing this PR! If you've already identified more minor typos, perhaps you can amend your changes to include these fixes as well? Thank you!

**Comment by szepeviktor** [comment]
You're welcome.

> more minor typos

This is the measurement result.
https://github.com/szepeviktor/typos-on-you/actions/runs/5693481260/job/15432666915
People like "invokable", so I've left that alone.

**Comment by clue** [comment]
> This is the measurement result.
> https://github.com/szepeviktor/typos-on-you/actions/runs/5693481260/job/15432666915

Very interesting rules and I really like the idea/concept, thank you for sharing!

> People like "invokable", so I've left that alone.

Interesting one as I couldn't find a definitive source, but it looks like both variants should indeed be fine (see https://en.wiktionary.org/wiki/invocable) and thus should not be reported, but we're probably out of scope of this ticket at this point :-)

In either case, thank you for the fixes again, keep it up! :+1:

**Review by clue — APPROVED** [review]

**Comment by szepeviktor** [comment]
> Very interesting rules and I really like the idea/concept, thank you for sharing!

You find dozens of goodies in this repo: https://github.com/szepeviktor/byte-level-care/tree/master/.github/workflows

**Comment by PaulRotmann** [comment]
Thanks for this PR, it’ll included in the next update! See #52. 🎯

**Pull request merged**
